"""Data gateways for local fixtures and Dozer's generated REST APIs."""

from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path
from typing import Any, Protocol
from urllib.request import Request, urlopen

from .models import CardProduct, CustomerFeatures, DataContractError


class CustomerNotFoundError(LookupError):
    pass


class GatewayError(RuntimeError):
    pass


class CardDataGateway(Protocol):
    source_name: str

    def get_customer_features(self, customer_id: str) -> CustomerFeatures: ...
    def list_card_products(self) -> list[CardProduct]: ...


def _read_csv(path: Path) -> list[dict[str, str]]:
    try:
        with path.open(encoding="utf-8", newline="") as handle:
            return list(csv.DictReader(handle))
    except (OSError, csv.Error) as exc:
        raise GatewayError(f"cannot read fixture {path.name}: {exc}") from exc


class FixtureGateway:
    """Compute the same customer feature contract from four local CSV datasets."""

    source_name = "fixture"

    def __init__(self, data_dir: Path | str) -> None:
        self.data_dir = Path(data_dir)

    def get_customer_features(self, customer_id: str) -> CustomerFeatures:
        customers = {row["customer_id"]: row for row in _read_csv(self.data_dir / "customers.csv")}
        customer = customers.get(customer_id)
        if customer is None:
            raise CustomerNotFoundError(customer_id)

        active_accounts = [
            row
            for row in _read_csv(self.data_dir / "accounts.csv")
            if row["customer_id"] == customer_id and row["status"].lower() == "active"
        ]
        account_ids = {row["account_id"] for row in active_accounts}
        totals: defaultdict[str, float] = defaultdict(float)
        for transaction in _read_csv(self.data_dir / "transactions.csv"):
            if transaction["account_id"] in account_ids:
                try:
                    totals[transaction["category"].lower()] += float(transaction["amount"])
                except ValueError as exc:
                    raise DataContractError("invalid transaction amount") from exc

        enriched: dict[str, Any] = {
            **customer,
            "monthly_spend": sum(totals.values()),
            "travel_spend": totals["travel"],
            "grocery_spend": totals["grocery"],
            "active_account": bool(active_accounts),
        }
        return CustomerFeatures.from_mapping(enriched)

    def list_card_products(self) -> list[CardProduct]:
        products = [
            CardProduct.from_mapping(row)
            for row in _read_csv(self.data_dir / "card_products.csv")
        ]
        if not products:
            raise GatewayError("card product fixture is empty")
        return products


class DozerGateway:
    """Consume only the two public APIs generated by dozer-config.yaml."""

    source_name = "dozer"

    def __init__(
        self,
        base_url: str = "http://localhost:8080",
        timeout: float = 5.0,
        max_response_bytes: int = 1_000_000,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.max_response_bytes = max_response_bytes

    def _request(self, path: str, payload: dict[str, Any] | None = None) -> Any:
        body = None if payload is None else json.dumps(payload).encode("utf-8")
        headers = {
            "Accept": "application/json",
            "User-Agent": "dozer-grounded-card-advisor/1",
        }
        if body is not None:
            headers["Content-Type"] = "application/json"
        request = Request(
            f"{self.base_url}{path}",
            data=body,
            headers=headers,
            method="POST" if body is not None else "GET",
        )
        try:
            with urlopen(request, timeout=self.timeout) as response:
                if response.status != 200:
                    raise GatewayError(f"Dozer returned HTTP {response.status}")
                body = response.read(self.max_response_bytes + 1)
                if len(body) > self.max_response_bytes:
                    raise GatewayError("Dozer response exceeds size limit")
                try:
                    return json.loads(body)
                except (json.JSONDecodeError, UnicodeDecodeError) as exc:
                    raise GatewayError("Dozer returned invalid JSON") from exc
        except GatewayError:
            raise
        except Exception as exc:
            raise GatewayError(f"Dozer request failed: {exc}") from exc

    def _get(self, path: str) -> Any:
        return self._request(path)

    def _post(self, path: str, payload: dict[str, Any]) -> Any:
        return self._request(path, payload)

    @staticmethod
    def _records(payload: Any) -> list[dict[str, Any]]:
        records: Any = None
        if isinstance(payload, list):
            records = payload
        elif isinstance(payload, dict):
            for key in ("records", "data", "values"):
                value = payload.get(key)
                if isinstance(value, list):
                    records = value
                    break
        if records is None or len(records) > 10_000:
            raise GatewayError("unexpected Dozer response shape")
        if not all(isinstance(record, dict) for record in records):
            raise GatewayError("unexpected Dozer record shape")
        return records

    def get_customer_features(self, customer_id: str) -> CustomerFeatures:
        records = self._records(
            self._post(
                "/customer_features/query",
                {"$filter": {"customer_id": customer_id}},
            )
        )
        matching = [row for row in records if str(row.get("customer_id")) == customer_id]
        if len(matching) != 1:
            if not matching:
                raise CustomerNotFoundError(customer_id)
            raise GatewayError("Dozer returned duplicate customer features")
        return CustomerFeatures.from_mapping(matching[0])

    def list_card_products(self) -> list[CardProduct]:
        products = [CardProduct.from_mapping(row) for row in self._records(self._get("/card_products"))]
        if not products:
            raise GatewayError("Dozer card_products API returned no records")
        return products
